Q1.Write a code to reverse a string?

In [ ]:
string = "pwskills"
string[::-1]

'sllikswp'

Q2.Write a code to count the number of vowels in a string?

In [ ]:
sentance = input("enter the sentance :")
string1 = sentance.lower()
print(string1)
count = 0
list = ["a","e","i","o","u"]
for char in string1:
  if char in list:
    count = count+1
print("number vowels in given sentence is:" ,count)

enter the sentance :wahidurrahaman
wahidurrahaman
number vowels in given sentence is: 6

In [ ]:
text = "Hello World"
text.lower()
print(text)
count = 0
list = ["a","e","i","o","u"]
for char in text:
  if char in list:
    count = count+1
print("number of vowels:" ,count)

Hello World
number of vowels: 3

Q3.Write a code to check if a given string is a palindrome or not?

In [ ]:
string = "pwskills"
reverse = string[::-1]
if(string == reverse):
  print("yes it is palindrome")
else:
    print("no it is not palindrome")

no it is not palindrome

# Q4.write a code to check if two given strings are anagrams of each other?

In [ ]:
str1 = input("enter string1")
str2 = input("enter string2")

if len(str1)!=len(str2):
  print("not anagrams")
else:
    if sorted(str1)==sorted(str2):
      print("strings are anagrams")
    else:
        print("not anagrams")

enter string1wahid
enter string2rahaman
not anagrams

Q5.Write a code to find all occurrences of a given substring within another string?

In [ ]:
def find_all_occurrences(main_string, substring):
    # Initialize an empty list to store the indices of occurrences
    indices = []

    # Start searching from the beginning of the string
    start = 0

    # Loop to find each occurrence of the substring
    while True:
        # Find the index of the substring starting from 'start'
        index = main_string.find(substring, start)

        # If find() returns -1, the substring is no longer found, break the loop
        if index == -1:
            break

        # Add the index to the list
        indices.append(index)

        # Move start to the next position after the found substring
        start = index + 1

    return indices

# Example usage:
main_string = input("Enter the main string: ")
substring = input("Enter the substring: ")

# Get all occurrences of the substring
occurrences = find_all_occurrences(main_string, substring)

# Output the result
if occurrences:
    print(f"The substring '{substring}' is found at indices: {occurrences}")
else:
    print(f"The substring '{substring}' is not found in the string.")

Enter the main string: how are you are
Enter the substring: are
The substring 'are' is found at indices: [4, 12]

Q6.Write a code to perform basic string compression using  the counts of repeated characters.

In [ ]:
def compress_string(s):
    # Edge case: if the string is empty, return it as is
    if not s:
        return s

    # Initialize the compressed string and a count variable
    compressed = []
    count = 1

    # Iterate through the string, starting from the second character
    for i in range(1, len(s)):
        # If the current character is the same as the previous one, increment the count
        if s[i] == s[i - 1]:
            count += 1
        else:
            # Otherwise, append the previous character and its count to the result
            compressed.append(s[i - 1] + str(count))
            count = 1  # Reset the count for the new character

    # Don't forget to append the last character and its count
    compressed.append(s[-1] + str(count))

    # Join the list into a string
    compressed_string = ''.join(compressed)

    # If the compressed string is not shorter, return the original string
    return compressed_string if len(compressed_string) < len(s) else s

# Example usage:
input_string = "aaabbbcccaaa"
result = compress_string(input_string)
print(result)  # Output: "a3b3c3a3"

a3b3c3a3

Q7.write a code to determine if a string has all unique characters.

In [ ]:
def has_unique_characters(s):
    # Create an empty set to track characters we've seen
    seen = set()

    # Iterate through each character in the string
    for char in s:
        # If the character is already in the set, return False
        if char in seen:
            return False
        # Otherwise, add the character to the set
        seen.add(char)

    # If we finish the loop without finding duplicates, return True
    return True

# Example usage:
input_string = "abcdefg"
result = has_unique_characters(input_string)
print(result)  # Output: True

input_string = "hello"
result = has_unique_characters(input_string)
print(result)  # Output: False

True
False

Q8.write a code to convert a given string to uppercase  or lowercase.

In [ ]:
def convert_string_case(s, to_upper=True):
    """
    Convert the string to either uppercase or lowercase based on the `to_upper` flag.

    :param s: The input string to convert.
    :param to_upper: If True, convert to uppercase. If False, convert to lowercase.
    :return: The string converted to the desired case.
    """
    if to_upper:
        return s.upper()  # Convert to uppercase
    else:
        return s.lower()  # Convert to lowercase

# Example usage:
input_string = "Hello, World!"

# Convert to uppercase
result_upper = convert_string_case(input_string, to_upper=True)
print("Uppercase:", result_upper)  # Output: "HELLO, WORLD!"

# Convert to lowercase
result_lower = convert_string_case(input_string, to_upper=False)
print("Lowercase:", result_lower)  # Output: "hello, world!"

Uppercase: HELLO, WORLD!
Lowercase: hello, world!

Q9.WRITE A CODE TO COUNT THE NUMBER OF WORDS IN A STRING

In [ ]:
s = "pwskills"
count = 0
for i in s:
    print(i)
    count = count+1
print(count)

p
w
s
k
i
l
l
s
8

Q10.WRITE A CODE TO CONCATENATE TWO STRINGS WITHOUT USING THE + OPERATOR.

In [ ]:
def concatenate_strings(str1, str2):
    return f"{str1}{str2}"

# Example usage
string1 = "Hello"
string2 = "World"
result = concatenate_strings(string1, string2)
print(result)  # Output: HelloWorld

HelloWorld

Q11.WRITE A CODE TO REMOVE ALL OCCURRENCES OF A SPECIFIC ELEMENTFROM A LIST.

In [ ]:
# Function to remove all occurrences of a specific element from the list
def remove_occurrences(lst, element):
    while element in lst:
        lst.remove(element)
    return lst

# Example usage
lst = [1, 2, 3, 4, 2, 5, 2, 6]
element_to_remove = int(input("Enter the element to remove: "))

# Remove all occurrences of the element
result_list = remove_occurrences(lst, element_to_remove)

# Print the modified list
print("List after removing all occurrences of", element_to_remove, ":", result_list)

Enter the element to remove: 5
List after removing all occurrences of 5 : [1, 2, 3, 4, 2, 2, 6]

Q12.Implement a code to find the second largest number in a given list of integers.

In [ ]:
def second_largest(numbers):
    # Remove duplicates by converting the list to a set and then back to a sorted list
    unique_numbers = sorted(set(numbers), reverse=True)

    # Check if the list has at least two distinct numbers
    if len(unique_numbers) < 2:
        return None  # Return None if there is no second largest number

    # Return the second element from the sorted list
    return unique_numbers[1]

def main():
    # Example list of integers
    numbers = [10, 20, 4, 45, 99, 45]

    # Find the second largest number
    result = second_largest(numbers)

    if result is not None:
        print(f"The second largest number is: {result}")
    else:
        print("There is no second largest number.")

# Run the main function
if __name__ == "__main__":
    main()

The second largest number is: 45

Q13.Create a code to count the occurrences of each element in a list and return a dictionary with elements as keys and their count as values.

In [ ]:
from collections import Counter

def count_occurrences(lst):
    # Use Counter to count occurrences and return the result as a dictionary
    return dict(Counter(lst))

def main():
    # Example list
    my_list = ['apple', 'banana', 'apple', 'cherry', 'banana', 'apple']

    # Count occurrences of each element in the list
    occurrences = count_occurrences(my_list)

    # Print the resulting dictionary
    print("Occurrences:", occurrences)

# Run the main function
if __name__ == "__main__":
    main()

Occurrences: {'apple': 3, 'banana': 2, 'cherry': 1}

Q14.Write a code to reverse a list in-place without using any built-in reverse functions.

In [ ]:
def reverse_list_in_place(lst):
    # Use two pointers to swap elements from both ends
    left = 0
    right = len(lst) - 1

    while left < right:
        # Swap the elements
        lst[left], lst[right] = lst[right], lst[left]

        # Move the pointers towards the center
        left += 1
        right -= 1

    return lst

def main():
    # Example list
    my_list = [1, 2, 3, 4, 5]

    # Reverse the list in place
    reversed_list = reverse_list_in_place(my_list)

    # Print the reversed list
    print("Reversed list:", reversed_list)

# Run the main function
if __name__ == "__main__":
    main()

Reversed list: [5, 4, 3, 2, 1]

Q15.Implement a code to find and remove duplicates from a list while preserving the original order of elements.

In [ ]:
def remove_duplicates(lst):
    seen = set()  # A set to track seen elements
    result = []   # List to store the result without duplicates

    for item in lst:
        if item not in seen:
            result.append(item)  # Add the item to the result list if it's not a duplicate
            seen.add(item)       # Mark this item as seen

    return result

def main():
    # Example list with duplicates
    my_list = [1, 2, 2, 3, 4, 4, 5, 1, 6, 3]

    # Remove duplicates while preserving the original order
    unique_list = remove_duplicates(my_list)

    # Print the list without duplicates
    print("List without duplicates:", unique_list)

# Run the main function
if __name__ == "__main__":
    main()

List without duplicates: [1, 2, 3, 4, 5, 6]

Q16.Create a code to check if a given given list is sorted.(either in ascending or descending order)or not.

In [ ]:
def is_sorted(lst):
    # Check if the list is sorted in ascending order
    if lst == sorted(lst):
        return "The list is sorted in ascending order."

    # Check if the list is sorted in descending order
    elif lst == sorted(lst, reverse=True):
        return "The list is sorted in descending order."

    # If neither condition is true, the list is not sorted
    else:
        return "The list is not sorted."

def main():
    # Example lists to check
    list1 = [1, 2, 3, 4, 5]
    list2 = [5, 4, 3, 2, 1]
    list3 = [1, 3, 2, 4, 5]

    # Check if each list is sorted
    print(is_sorted(list1))  # Sorted in ascending order
    print(is_sorted(list2))  # Sorted in descending order
    print(is_sorted(list3))  # Not sorted

# Run the main function
if __name__ == "__main__":
    main()

The list is sorted in ascending order.
The list is sorted in descending order.
The list is not sorted.

Q17.Write a code to merge two sorted lists into a single sorted list.

In [ ]:
def merge_sorted_lists(list1, list2):
    # Initialize pointers for both lists and the result list
    i, j = 0, 0
    merged_list = []

    # Loop through both lists and compare elements
    while i < len(list1) and j < len(list2):
        if list1[i] < list2[j]:
            merged_list.append(list1[i])
            i += 1
        else:
            merged_list.append(list2[j])
            j += 1

    # If any elements remain in list1, add them to the merged list
    while i < len(list1):
        merged_list.append(list1[i])
        i += 1

    # If any elements remain in list2, add them to the merged list
    while j < len(list2):
        merged_list.append(list2[j])
        j += 1

    return merged_list

def main():
    # Example sorted lists
    list1 = [1, 3, 5, 7]
    list2 = [2, 4, 6, 8]

    # Merge the two sorted lists
    result = merge_sorted_lists(list1, list2)

    # Print the merged list
    print("Merged list:", result)

# Run the main function
if __name__ == "__main__":
    main()

Merged list: [1, 2, 3, 4, 5, 6, 7, 8]

Q18.Implement a code to find the intersection of two given lists.

In [ ]:
def intersection_of_lists(list1, list2):
    # Convert both lists to sets to remove duplicates and perform the intersection
    set1 = set(list1)
    set2 = set(list2)

    # Find the intersection of both sets
    intersection = set1 & set2

    # Convert the result back to a list to return it
    return list(intersection)

def main():
    # Example lists
    list1 = [1, 2, 3, 4, 5]
    list2 = [4, 5, 6, 7, 8]

    # Find the intersection of the two lists
    result = intersection_of_lists(list1, list2)

    # Print the result
    print("Intersection:", result)

# Run the main function
if __name__ == "__main__":
    main()

Intersection: [4, 5]

19.Create a code to find the union of two lists without duplicates.

In [ ]:
def union_of_lists(list1, list2):
    # Convert both lists to sets to remove duplicates
    set1 = set(list1)
    set2 = set(list2)

    # Find the union of both sets
    union = set1 | set2  # Alternatively, you could use set1.union(set2)

    # Convert the result back to a list and return it
    return list(union)

def main():
    # Example lists
    list1 = [1, 2, 3, 4, 5]
    list2 = [4, 5, 6, 7, 8]

    # Find the union of the two lists
    result = union_of_lists(list1, list2)

    # Print the result
    print("Union of the lists:", result)

# Run the main function
if __name__ == "__main__":
    main()

Union of the lists: [1, 2, 3, 4, 5, 6, 7, 8]

Q20.Write a code to shuffle a given list randomly without using any built-in shuffle functions.

In [ ]:
import random

def shuffle_list(lst):
    # Fisher-Yates (Knuth) Shuffle
    n = len(lst)

    # Iterate over the list in reverse order
    for i in range(n - 1, 0, -1):
        # Pick a random index between 0 and i (inclusive)
        j = random.randint(0, i)

        # Swap the elements at indices i and j
        lst[i], lst[j] = lst[j], lst[i]

    return lst

def main():
    # Example list to shuffle
    my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]

    # Shuffle the list
    shuffled_list = shuffle_list(my_list)

    # Print the shuffled list
    print("Shuffled list:", shuffled_list)

# Run the main function
if __name__ == "__main__":
    main()

Shuffled list: [8, 4, 6, 2, 7, 9, 3, 1, 5]

Q21.Write a code that takes two tuples as input and returns a new tuple containing elements that are common to both input tuples.

In [ ]:
def common_elements(tuple1, tuple2):
    # Use set intersection to find common elements
    common = set(tuple1) & set(tuple2)

    # Return the common elements as a tuple
    return tuple(common)

# Example usage
tuple1 = (1, 2, 3, 4, 5)
tuple2 = (4, 5, 6, 7, 8)

result = common_elements(tuple1, tuple2)
print(result)  # Output: (4, 5)

(4, 5)

Q22.Create a code that prompts the user to enter two sets of integers separated by commas. Then, print the intersection of these two sets.

In [ ]:
def get_input_set(prompt):
    # Prompt the user to enter a set of integers separated by commas
    user_input = input(prompt)

    # Convert the input string to a list of integers
    num_list = [int(x.strip()) for x in user_input.split(',')]

    # Return the set created from the list of integers
    return set(num_list)

# Get two sets of integers from the user
set1 = get_input_set("Enter the first set of integers (separated by commas): ")
set2 = get_input_set("Enter the second set of integers (separated by commas): ")

# Find the intersection of the two sets
intersection = set1 & set2

# Print the result
print("The intersection of the two sets is:", intersection)

Enter the first set of integers (separated by commas): 1,2,3,4,5
Enter the second set of integers (separated by commas): 4,5,6,7
The intersection of the two sets is: {4, 5}

Q23.Write a code to concatenate two tuples. The function should take two tuples as input and return a new tuple containing elements from both input tuples.

In [ ]:
def concatenate_tuples(tuple1, tuple2):
    # Concatenate the two tuples
    return tuple1 + tuple2

# Example usage
tuple1 = (1, 2, 3)
tuple2 = (4, 5, 6)

result = concatenate_tuples(tuple1, tuple2)
print(result)  # Output: (1, 2, 3, 4, 5, 6)

(1, 2, 3, 4, 5, 6)

Q24.Develop a code that prompts the user to input two sets of strings. Then,print the elements that are present in the first set but not in the second set

In [ ]:
def get_input_set(prompt):
    # Prompt the user to input a set of strings separated by commas
    user_input = input(prompt)

    # Convert the input string to a list of strings and strip any leading/trailing spaces
    string_list = [x.strip() for x in user_input.split(',')]

    # Return the set created from the list of strings
    return set(string_list)

# Get two sets of strings from the user
set1 = get_input_set("Enter the first set of strings (separated by commas): ")
set2 = get_input_set("Enter the second set of strings (separated by commas): ")

# Find elements that are in set1 but not in set2 (set difference)
difference = set1 - set2

# Print the result
print("The elements present in the first set but not in the second set are:", difference)

Enter the first set of strings (separated by commas): apple, banana, cherry, date
Enter the second set of strings (separated by commas):  banana, date, elderberry
The elements present in the first set but not in the second set are: {'apple', 'cherry'}

Q25.Create a code that takes a tuple and two integers as input. The function should return a new tuple containing elements from the original tuple within the specified range of indices.

In [ ]:
def slice_tuple(input_tuple, start_index, end_index):
    # Return a new tuple containing elements within the specified index range
    return input_tuple[start_index:end_index]

# Example usage:
input_tuple = (10, 20, 30, 40, 50, 60)
start_index = int(input("Enter the start index: "))
end_index = int(input("Enter the end index: "))

result = slice_tuple(input_tuple, start_index, end_index)
print("The new tuple with elements in the specified range is:", result)

Enter the start index: 1
Enter the end index: 4
The new tuple with elements in the specified range is: (20, 30, 40)

Q26.Write a code that prompts the user to input two set of characters. Then print the union of these two sets.

In [ ]:
def get_input_set(prompt):
    # Prompt the user to input a set of characters separated by commas
    user_input = input(prompt)

    # Convert the input string to a set of characters (remove any spaces if necessary)
    return set(user_input.strip())

# Get two sets of characters from the user
set1 = get_input_set("Enter the first set of characters: ")
set2 = get_input_set("Enter the second set of characters: ")

# Find the union of the two sets
union_set = set1 | set2

# Print the result
print("The union of the two sets is:", union_set)

Enter the first set of characters: abcde
Enter the second set of characters: defgh
The union of the two sets is: {'a', 'e', 'h', 'b', 'd', 'g', 'f', 'c'}

Q27.Develop a code that takes a tuple of integers as input. The function should return the maximum and minimum values from the tuple using tuple unpacking.

In [ ]:
def find_max_min(input_tuple):
    # Use the built-in min() and max() functions to find the minimum and maximum values
    min_val, max_val = min(input_tuple), max(input_tuple)

    return min_val, max_val

# Example usage
input_tuple = tuple(map(int, input("Enter a tuple of integers separated by spaces: ").split()))

# Unpack the returned values
min_value, max_value = find_max_min(input_tuple)

print("The minimum value in the tuple is:", min_value)
print("The maximum value in the tuple is:", max_value)

Enter a tuple of integers separated by spaces: 1 2 3 4 5 6 7
The minimum value in the tuple is: 1
The maximum value in the tuple is: 7

Q28.Create a code that defines two sets of integers. Then, print the union, intersection, and difference of these two sets.

In [ ]:
# Define two sets of integers
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}

# Union of set1 and set2 (all unique elements from both sets)
union_set = set1 | set2

# Intersection of set1 and set2 (elements common to both sets)
intersection_set = set1 & set2

# Difference of set1 and set2 (elements in set1 but not in set2)
difference_set = set1 - set2

# Print the results
print("Union of set1 and set2:", union_set)
print("Intersection of set1 and set2:", intersection_set)
print("Difference of set1 and set2 (set1 - set2):", difference_set)

Union of set1 and set2: {1, 2, 3, 4, 5, 6, 7, 8}
Intersection of set1 and set2: {4, 5}
Difference of set1 and set2 (set1 - set2): {1, 2, 3}

Q29.Write a code that takes a tuple and an element as input. The function should return the count of occurrences of the given element in the tuple.

In [ ]:
def count_occurrences(input_tuple, element):
    # Use the count() method to return the number of occurrences of the element in the tuple
    return input_tuple.count(element)

# Example usage:
input_tuple = tuple(map(int, input("Enter a tuple of integers (separated by spaces): ").split()))
element = int(input("Enter the element to count occurrences of: "))

result = count_occurrences(input_tuple, element)
print(f"The element {element} appears {result} time(s) in the tuple.")

Enter a tuple of integers (separated by spaces): 1 2 3 4 5 2 2 6
Enter the element to count occurrences of: 2
The element 2 appears 3 time(s) in the tuple.

Q30.Develop a code that prompts the user to input two sets of strings. Then, print the symmetric difference of these two sets.

In [ ]:
def get_input_set(prompt):
    # Prompt the user for a set of strings and split by space to form a list, then convert it to a set
    user_input = input(prompt)
    input_list = user_input.split()
    return set(input_list)

def main():
    # Prompt the user to input two sets of strings
    set1 = get_input_set("Enter the first set of strings (space-separated): ")
    set2 = get_input_set("Enter the second set of strings (space-separated): ")

    # Calculate the symmetric difference of the two sets
    symmetric_difference = set1 ^ set2  # Alternatively, use set1.symmetric_difference(set2)

    # Print the result
    print("The symmetric difference of the two sets is:", symmetric_difference)

# Run the main function
if __name__ == "__main__":
    main()

Enter the first set of strings (space-separated): apple banana cherry
Enter the second set of strings (space-separated): banana cherry date
The symmetric difference of the two sets is: {'apple', 'date'}

Q31.Write a code that takes a list of words as input and returns a dictionary where the keys are unique words and the values are the frequencies of those words in the input list.

In [ ]:
def count_word_frequencies(word_list):
    word_count = {}  # Initialize an empty dictionary to store word frequencies

    # Iterate over each word in the list
    for word in word_list:
        if word in word_count:
            # If the word is already in the dictionary, increment its count
            word_count[word] += 1
        else:
            # If the word is not in the dictionary, add it with a count of 1
            word_count[word] = 1

    return word_count

def main():
    # Example list of words
    words = ["apple", "banana", "apple", "orange", "banana", "apple", "kiwi"]

    # Get the word frequencies
    result = count_word_frequencies(words)

    # Print the word frequencies
    print("Word Frequencies:", result)

# Run the main function
if __name__ == "__main__":
    main()

Word Frequencies: {'apple': 3, 'banana': 2, 'orange': 1, 'kiwi': 1}

Q32.Write a code that takes two dictionaries as input and merges them into a single dictionary.If there are common keys, the value should be added together.

In [ ]:
def merge_dicts(dict1, dict2):
    # Create a new dictionary to store the merged result
    merged_dict = dict1.copy()  # Start with a copy of dict1

    # Iterate over the second dictionary and add values to the merged dictionary
    for key, value in dict2.items():
        if key in merged_dict:
            merged_dict[key] += value  # If the key exists, add the value
        else:
            merged_dict[key] = value  # If the key doesn't exist, just add it

    return merged_dict

def main():
    # Example input for two dictionaries
    dict1 = {'apple': 10, 'banana': 5, 'cherry': 3}
    dict2 = {'banana': 7, 'cherry': 2, 'date': 4}

    # Merge the dictionaries
    result = merge_dicts(dict1, dict2)

    # Print the result
    print("Merged dictionary:", result)

# Run the main function
if __name__ == "__main__":
    main()

Merged dictionary: {'apple': 10, 'banana': 12, 'cherry': 5, 'date': 4}

Q33.Write a code to access a value in a nested dictionary. The function should take the dictionary and a list of keys as input, and return the corresponding value. If any of the keys do not exist in the dictionary, the function should return None.

In [ ]:
def access_nested_value(d, keys):
    # Iterate over the list of keys
    for key in keys:
        # Check if the key exists in the current dictionary level
        if isinstance(d, dict) and key in d:
            d = d[key]  # Move to the next level of the dictionary
        else:
            return None  # Return None if the key is not found or if it's not a dictionary
    return d  # Return the final value found

def main():
    # Example of a nested dictionary
    nested_dict = {
        'a': {
            'b': {
                'c': 5
            },
            'd': 10
        },
        'e': 20
    }

    # Example input for keys
    keys1 = ['a', 'b', 'c']
    keys2 = ['a', 'x']  # Invalid key path

    # Access values using the keys
    value1 = access_nested_value(nested_dict, keys1)
    value2 = access_nested_value(nested_dict, keys2)

    # Print the results
    print(f"Value for keys {keys1}: {value1}")  # Output: 5
    print(f"Value for keys {keys2}: {value2}")  # Output: None

# Run the main function
if __name__ == "__main__":
    main()

Value for keys ['a', 'b', 'c']: 5
Value for keys ['a', 'x']: None

Q34.Write a code that takes a dictionary as input and returns a sorted version of it based on the values. You can choose whether to sort in ascending or descending order.

In [ ]:
def sort_dict_by_value(d, descending=False):
    # Sort the dictionary by values, and return a sorted dictionary
    # Use sorted() and pass a lambda function to sort by values
    sorted_items = sorted(d.items(), key=lambda item: item[1], reverse=descending)

    # Convert the sorted items back into a dictionary
    sorted_dict = dict(sorted_items)

    return sorted_dict

def main():
    # Example dictionary
    my_dict = {'apple': 10, 'banana': 5, 'cherry': 20, 'date': 15}

    # Sort the dictionary in ascending order by value
    sorted_asc = sort_dict_by_value(my_dict, descending=False)
    print("Sorted by value (ascending):", sorted_asc)

    # Sort the dictionary in descending order by value
    sorted_desc = sort_dict_by_value(my_dict, descending=True)
    print("Sorted by value (descending):", sorted_desc)

# Run the main function
if __name__ == "__main__":
    main()

Sorted by value (ascending): {'banana': 5, 'apple': 10, 'date': 15, 'cherry': 20}
Sorted by value (descending): {'cherry': 20, 'date': 15, 'apple': 10, 'banana': 5}

Q35.Write a code that inverts a dictionary, swapping keys and values. Ensure that the inverted dictionary correctly handles cases where multiple keys have the same value by storing the keys as a list in the inverted dictionary.

In [ ]:
def invert_dict(d):
    # Create an empty dictionary to store the inverted key-value pairs
    inverted_dict = {}

    # Iterate over the items in the original dictionary
    for key, value in d.items():
        if value in inverted_dict:
            # If the value is already a key in the inverted dictionary, append the key to the list
            inverted_dict[value].append(key)
        else:
            # Otherwise, add a new entry with the value as the key and the key as a list
            inverted_dict[value] = [key]

    return inverted_dict

def main():
    # Example dictionary
    my_dict = {'apple': 10, 'banana': 5, 'cherry': 10, 'date': 15}

    # Invert the dictionary
    inverted = invert_dict(my_dict)

    # Print the inverted dictionary
    print("Inverted dictionary:", inverted)

# Run the main function
if __name__ == "__main__":
    main()

Inverted dictionary: {10: ['apple', 'cherry'], 5: ['banana'], 15: ['date']}

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# New Section